In [2]:
import torch
from torch import nn
from d2l import torch as d2l

# 1. 基本操作

In [3]:
"""
 X: 输入张量
 K: 卷积核
"""
def trans_conv(X, K):
    h, w = K.shape
    Y = torch.zeros((X.shape[0] + h - 1, X.shape[1] + w - 1))
    for i in range(X.shape[0]):
        for j in range(X.shape[1]):
            Y[i: i + h, j: j + w] += X[i, j] * K
    return Y

In [4]:
X = torch.tensor([[0.0, 1.0], [2.0, 3.0]])
K = torch.tensor([[0.0, 1.0], [2.0, 3.0]])
print(X)
print(K)
trans_conv(X, K)

tensor([[0., 1.],
        [2., 3.]])
tensor([[0., 1.],
        [2., 3.]])


tensor([[ 0.,  0.,  1.],
        [ 0.,  4.,  6.],
        [ 4., 12.,  9.]])

In [5]:
X, K = X.reshape(1, 1, 2, 2), K.reshape(1, 1, 2, 2)
print(X)
print(K)

## 定义一个转置卷积层，输入和输出通道数为 1，卷积核大小为 2x2
tconv = nn.ConvTranspose2d(1, 1, kernel_size=2, bias=False)
tconv.weight.data = K
tconv(X)

tensor([[[[0., 1.],
          [2., 3.]]]])
tensor([[[[0., 1.],
          [2., 3.]]]])


tensor([[[[ 0.,  0.,  1.],
          [ 0.,  4.,  6.],
          [ 4., 12.,  9.]]]], grad_fn=<ConvolutionBackward0>)

In [6]:
# 定义一个转置卷积层，输入和输出通道数为 1，卷积核大小为 2x2，padding=1
tconv = nn.ConvTranspose2d(1, 1, kernel_size=2, padding=1, bias=False)
tconv.weight.data = K
tconv(X)

tensor([[[[4.]]]], grad_fn=<ConvolutionBackward0>)